In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [8]:
x = []
for i in range(100):
    x.append(i)

X = np.array(x)

In [13]:
Y = np.random.randint(2, size=100)

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [16]:
X_train, len(X_train)

(array([89, 12, 90,  7, 47, 14, 98, 36, 58, 67,  8, 28, 29, 75, 60, 82, 16,
        91, 51, 33, 43, 76, 48, 19, 27, 17, 62, 73, 31, 87, 39, 49, 41, 46,
        30, 77, 42, 63,  5, 23, 85, 72,  0, 32, 94, 18, 54, 81, 65, 69, 52,
         9, 95, 35, 93, 68, 84, 66, 13,  1, 20, 64, 22, 38, 21,  4,  3, 78,
        99, 88, 50, 44, 96,  2, 70, 11, 40, 83, 71, 55]),
 80)

In [17]:
Y_train, len(Y_train)

(array([0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1], dtype=int32),
 80)

In [18]:
X_test, len(X_test)

(array([79, 57, 56, 97, 74,  6, 15, 53, 37, 59, 26, 25, 45, 24, 92, 86, 80,
        61, 10, 34]),
 20)

In [19]:
Y_test, len(Y_test)

(array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1],
       dtype=int32),
 20)